# --- docker-compose.yml ---
version: "3.9"

services:
  web:
    build: .
    container_name: webhook_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    container_name: webhook_worker
    command: ["./wait-for-redis.sh", "celery", "-A", "app.celery_worker.celery_app", "worker", "--loglevel=info", "--pool=solo"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    container_name: webhook_beat
    command: ["./wait-for-redis.sh", "celery", "-A", "app.celery_worker.celery_app", "beat", "--loglevel=info"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    container_name: webhook_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: datahack
      POSTGRES_DB: Webhook
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
